### PR TITLE
Added ARS currency support + replace hardcoded array length for variable

### PR DESCRIPTION
**Pull request by marianomontano**

### CODE REVIEW

**Review by SubhadeepJasu — COMMENTED** [review]
You will also need to add the option in this file: https://github.com/SubhadeepJasu/pebbles/blob/master/src/Views/ConvCurrView.vala. Only then it will appear.

**Comment by marianomontano** [comment]
rigth! sorry about that.
Also for some reason it's not compiling when retrieving the array length with currency.length.
Had to hard-code it againg. :/

**Comment by SubhadeepJasu** [comment]
The array itself is hardcoded, so I think its okay to hardcode the length.

**Comment by SubhadeepJasu** [comment]
Thank you!🎉

**Pull request merged**
