### PR TITLE
Use explicit Mach to meter/second conversion factor

### PR DESCRIPTION
**Pull request by cydanil**
Hi, 

Thank your for pebbles! I really like it and it's nice to have a single application to go to for various tasks.  

I noticed that there was an issue with converting Mach speeds to other units, as shown in the figures below.  
This could be resolved by making use of the floating point value directly, rather than the ratio.  

I'm not sure exactly what causes this behaviour (it's my first PR using vala), but I'm keen to work it out should you have a better approach.  

Thanks!
Cyril

Using master, the following result is produced:

image

image

It's also true with other units:

image

The proposed fix calculates correct results:

image

### CODE REVIEW

**Comment by SubhadeepJasu** [comment]
Hi. Thanks for the pull request. Users have reported similar issue in other converters too. We can definitely work towards fixing that. I am curious how the solution works (I must have overlooked something), but at the end of the day if it works reliably that's all that matters. If this works then we can finally fix all the other converters as well.

**Comment by cydanil** [comment]
Ah, I figured what the issue is: as the division is operated on two integers, the quotient is an integer, `0`, which is used subsequently in all operations. 
To get a double out, one of the operands must explicitly be cast to `double`.

This is shown in the code below:

```vala
class Test : GLib.Object {

    private const double[] unit_multipliers = {
        (1/343),
        ((double) 1/343),  // or (double) 1/343,
    };

    public static int main(string[] args) {
        double first = unit_multipliers[0]; 
        stdout.printf(@"$first\n");
        double other = unit_multipliers[1];
        stdout.printf(@"$other");
        
        return 0;
    }
}
```

The first print will print `0`, and the second will correctly print `0.0029154518950437317`.  

I will update the PR accordingly later.

**Comment by cydanil** [comment]
I think that's all of them.  
These should close #50

**Comment by SubhadeepJasu** [comment]
I made a few fixes to the Utils.vala file locally, this resolves some of the issues with data converter. Can you retroactively add them in your pull request? Thanks
Screenshot from 2021-09-13 09 17 52
Screenshot from 2021-09-13 09 18 54

**Comment by SubhadeepJasu** [comment]
```Vala
if (!result.contains(Utils.get_local_radix_symbol ())) {
    output += Utils.get_local_radix_symbol () + "0";
}
```

```Vala
switch (accuracy) {
    case 10:
        output = ("%.10lf".printf (result));
        break;
    case 9:
        output = ("%.9lf".printf (result));
        break;
    case 8:
        output = ("%.8lf".printf (result));
        break;
    case 7:
        output = ("%.7lf".printf (result));
        break;
    case 6:
        output = ("%.6lf".printf (result));
        break;
    case 5:
        output = ("%.5lf".printf (result));
        break;
    case 4:
        output = ("%.4lf".printf (result));
        break;
    case 3:
        output = ("%.3lf".printf (result));
        break;
    case 2:
        output = ("%.2lf".printf (result));
        break;
    case 1:
        output = ("%.1lf".printf (result));
        break;
    case 0:
        output = ((int) result).to_string();
        break;
    default:
        output = result.to_string ();
        break;
}
```

**Comment by cydanil** [comment]
Thanks,  
I made your changes and checked they work as expected by converting 20 minutes to hours and seeing the correct radix symbol and trying different accuracy resolutions.

**Comment by SubhadeepJasu** [comment]
Thanks a lot m8. I'll merge this in soon.

**Comment by SubhadeepJasu** [comment]
Made some changes. I changed the casts to double constants. If you are okay with the changes I'll merge, let me know if you see any problems.

**Comment by cydanil** [comment]
Yeah sure, it makes more sense, I used casting because I was happy I figured it out ;)

LGTM

**Pull request merged**
